### PR TITLE
Codeowners feature

### PR DESCRIPTION
**Pull request by tareq97**
As per Issue #514 created a CODEOWNERS files.

### CODE REVIEW

**Comment by pablo-de-andres** [comment]
Thanks for the PR!
@urbanmatthias is not available for now, so he'll review it when he is back 😄 
(Also, I think maybe I should be a codeowner as well)

**Comment by tareq97** [comment]
> Thanks for the PR!
> @urbanmatthias is not available for now, so he'll review it when he is back smile
> (Also, I think maybe I should be a codeowner as well)

Hi @pablo-de-andres,

Thanks for the reply. Added you in the list too.

**Comment by pablo-de-andres** [comment]
Did you fork from master? We usually use a `dev` branch (in this case [v3.5.0-dev](https://github.com/simphony/osp-core/tree/v3.5.0-dev)) and do all the changes there. Then release to master.
And I think this file might be better placed inside `.github/`. But let's wait to see what @urbanmatthias says next week.

**Comment by tareq97** [comment]
hi @pablo-de-andres,

Yes I did fork the master branch. I was not aware of raising the pull request on dev branch. This pull request can be closed so that I can raise a new pull request for dev branch and put the CODEOWNERS file in .github/ folder as per your request.

**Comment by tareq97** [comment]
Hi @pablo-de-andres,

Just an update, I have created one more PR #538 for moving the CODEOWNERS file in the dev branch first.

This PR #537 can be closed with out merging. PR #538 can be used to merge the /.github/CODEOWNERS file in the dev branch in future when @urbanmatthias is back.

Thank you :smiley:

**Pull request closed without merging**
