### PR TITLE
Fix issue 560 "format of ontology is not stored properly"

### LINKED ISSUE #560: format of ontology is not stored properly
After installing an ontology in a turtle format, an XML file is generated in the `~/.osp-ontologies` directory, but the format that is specified in the accompanying configuration yml file specifies the format not as XML, but as turtle format.

### PR DESCRIPTION
**Pull request by yoavnash**
Closes #560

### CODE REVIEW

**Comment by pablo-de-andres** [comment]
Is there a unittest for it as well?

**Comment by yoavnash** [comment]
Just created one, but it failed. Not sure why

**Comment by pablo-de-andres** [comment]
Could be that there are not runners 😅

**Comment by yoavnash** [comment]
What can be done?

**Comment by pablo-de-andres** [comment]
Done. Tests run (successfully)

**Comment by yoavnash** [comment]
Seems to work. Thanks.
@urbanmatthias can you check and merge if all is ok?

**Review by urbanmatthias — APPROVED** [review]

**Pull request merged**
