### PR TITLE
652 cuba.file in dataspace session shows wrong file path on second load

### LINKED ISSUE #652: cuba.File in DataspaceSession shows wrong file path on second load
This is a bit difficult to reproduce, since it requires a running DSMS server. The example shown uses the local docker version from the DSMS repo. 

In the following example:

```
picture_file = '3.png'

with DataspaceSession(conn_text, connect_kwargs=connect_kwargs, dataspace_name=PRIVATE_DATASPACE_DB_NAME, file_destination="client_files") as session:
    wrapper = cuba.Wrapper(session=session)
    
    f2 = cuba.File(path=picture_file)

    wrapper.add(f2, rel=cuba.activeRelationship)
    wrapper.session.commit()
```

The file loaded shows the expected path of the file on the local machine.

```
with DataspaceSession(conn_text, connect_kwargs=connect_kwargs, dataspace_name=PRIVATE_DATASPACE_DB_NAME, file_destination="client_files") as session:
    wrapper = cuba.Wrapper(session=session)

    f2 = wrapper.get(f2.uid)
    print(f2.path)

>>> client_files/c2ec7e1db7b44ecbb34e930767d040dd-3.png
```

The second time the identical code is used the path is from the remote machine.
```
with DataspaceSession(conn_text, connect_kwargs=connect_kwargs, dataspace_name=PRIVATE_DATASPACE_DB_NAME, file_destination="client_files") as session:
    wrapper = cuba.Wrapper(session=session)

    f2 = wrapper.get(f2.uid)
    print(f2.path)

>>> /sqlite-db/user-file-uploads/c2ec7e1db7b44ecbb34e930767d040dd-3.png
```

After some digging is found, that if the actual file is not yet copied to file_destination the local path is shown, but if the file is already copied, e.g. calling the wrapper again, the remote path is shown. 
I assume this is not intended behavior.

### PR DESCRIPTION
**Pull request by kysrpex**
Closes #652.

### CODE REVIEW

**Comment by kysrpex** [comment]
Before merging:

- [ ] 1. Merge PR #664 to `dev`.
- [ ] 2. Merge `dev` into this PR's branch.
- [ ] 3. Uncomment the commented part of the `test_download` function in `test_filetransfer.py`(from this PR's branch) and then commit the changes to this PR's branch.

The tests should pass and then this PR can be merged.

**Review by yoavnash — COMMENTED** [review]
@paulzierep please have a look and confirm it save your problem. Note that there might be a dependency on https://github.com/simphony/osp-core/pull/664, as already mentioned by Jose.

**Comment by kysrpex** [comment]
> @paulzierep please have a look and confirm it save your problem. Note that there might be a dependency on #664, as already mentioned by Jose.

@yoavnash Do not worry, there is not really a dependency (otherwise I would have based this branch on the other). It is just that since both affect the file names, the automated tests "conflict", so rather than merging both and then touching the tests on another PR, I prefer to just uncomment the tests here. In fact, I already tried the commented part locally with both branches merged.

Testing the feature just on this branch is fine.

**Comment by paulzierep** [comment]
I can confirm this solves the problem on the client side. The path is now shown correctly.

**Review by yoavnash — APPROVED** [review]

**Pull request merged**
