### PR TITLE
Issues with latest EMMO Fixes #503

### LINKED ISSUE #503: Issues with latest EMMO
```
In [10]: math.Numerical.attributes
AttributeError                            Traceback (most recent call last)

<ipython-input-10-3f8afffaad6c> in <module>
----> 1 math.Numerical.attributes

~/projects/Marketplace/python-environments/osp_core_env/lib/python3.7/site-packages/osp/core/ontology/oclass.py in attributes(self)
     29         attributes = dict()
     30         for superclass in self.superclasses:
---> 31             attributes.update(self._get_attributes(superclass.iri))
     32         return attributes
     33 

AttributeError: 'NoneType' object has no attribute 'iri'https://raw.githubusercontent.com/emmo-repo/emmo-repo.github.io/master/versions/1.0.0-alpha2/emmo-inferred.owl
```

Using: https://raw.githubusercontent.com/emmo-repo/emmo-repo.github.io/master/versions/1.0.0-alpha2/emmo-inferred.owl

### PR DESCRIPTION
**Pull request by urbanmatthias**

### CODE REVIEW

**Comment by urbanmatthias** [comment]
@aaronAB1993 Can you verify that this works for you?

We had an error report with this version of emmo:

```
In [10]: math.Numerical.attributes
AttributeError                            Traceback (most recent call last)

<ipython-input-10-3f8afffaad6c> in <module>
----> 1 math.Numerical.attributes

~/projects/Marketplace/python-environments/osp_core_env/lib/python3.7/site-packages/osp/core/ontology/oclass.py in attributes(self)
     29         attributes = dict()
     30         for superclass in self.superclasses:
---> 31             attributes.update(self._get_attributes(superclass.iri))
     32         return attributes
     33 

AttributeError: 'NoneType' object has no attribute 'iri'https://raw.githubusercontent.com/emmo-repo/emmo-repo.github.io/master/versions/1.0.0-alpha2/emmo-inferred.owl
```

**Comment by aaronAB1993** [comment]
I cannot reproduce it. I get the latest osp-core dev version, I install it, I install emmo, I run:
```python
from osp.core.namespaces import math
math.Numerical.attributes
```
And I get:
```console
{<OntologyAttribute math.hasNumericalData>: None}
```
Which I assume is supossed to happen?

**Comment by aaronAB1993** [comment]
@urba according to the description in the issue, I guess you want me to test this emmo version: 
https://raw.githubusercontent.com/emmo-repo/emmo-repo.github.io/master/versions/1.0.0-alpha2/emmo-inferred.owl

How do I manually install it? Copy paste to the definition yaml?

**Comment by urbanmatthias** [comment]
I think I updated the URL in the branch https://github.com/simphony/osp-core/tree/urbanmatthias/issue503

**Comment by aaronAB1993** [comment]
Still works for me on the feature branch

**Comment by urbanmatthias** [comment]
Okay then I'll merge this. Maybe I can get more information about the error.

**Pull request merged**
